### ISSUE TITLE
ImportError when using SchemaRegistryClient

### ISSUE THREAD

**Issue by pederpansen** [Landoop/python-serializers#7]
Hi, i get the following error when trying to use the `SchemaRegistryClient`:

```
Traceback (most recent call last):
  File "get_timerange.py", line 8, in <module>
    from datamountaineer.schemaregistry.client import SchemaRegistryClient
  File "/Volumes/data/home/.pyenv/versions/3.5.2/lib/python3.5/site-packages/datamountaineer/schemaregistry/client/__init__.py", line 1, in <module>
    from .SchemaRegistryClient import *
  File "/Volumes/data/home/.pyenv/versions/3.5.2/lib/python3.5/site-packages/datamountaineer/schemaregistry/client/SchemaRegistryClient.py", line 8, in <module>
    from ..serializers import Util
  File "/Volumes/data/home/.pyenv/versions/3.5.2/lib/python3.5/site-packages/datamountaineer/schemaregistry/serializers/__init__.py", line 14, in <module>
    from .MessageSerializer import *
  File "/Volumes/data/home/.pyenv/versions/3.5.2/lib/python3.5/site-packages/datamountaineer/schemaregistry/serializers/MessageSerializer.py", line 1, in <module>
    from fastavro.reader import read_data
ImportError: No module named 'fastavro.reader'
```

Is the `fastavro` version I am using (0.17.1) too new? (Downgrading to fastavro 0.16.3 works.)

**Comment by andrewstevenson** [comment]
@pederpansen We aren't actively supporting this anymore asw e promote going via websockets and Rest against Lenses which handles this for and allows you to write SQL statements. https://www.landoop.com/kafka-lenses/

**Comment by Neelotpaul** [comment]
Any luck with this. I have installed datamountaineer_schemaregistry from python-serializers-master zip file.
I try to import the

 >>> from datamountaineer.schemaregistry.serializers import MessageSerializer, Util
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\neelotpaulroy\AppData\Local\Continuum\anaconda3\lib\site-packages\datamountaineer_schemaregistry-0.3-py3.6.egg\datamountaineer\schemaregistry\serializers\__init__.py", line 14, in <module>
    from .MessageSerializer import *
  File "C:\Users\neelotpaulroy\AppData\Local\Continuum\anaconda3\lib\site-packages\datamountaineer_schemaregistry-0.3-py3.6.egg\datamountaineer\schemaregistry\serializers\MessageSerializer.py", line 1, in <module>
    from fastavro.reader import read_data
ModuleNotFoundError: No module named 'fastavro.reader'

I checked with 

(base) C:\Users\neelotpaulroy>pip install fastavro
Requirement already satisfied: fastavro in c:\users\neelotpaulroy\appdata\local\continuum\anaconda3\lib\site-packages\fastavro-0.17.10-py3.6-win-amd64.egg
Requirement already satisfied: Cython in c:\users\neelotpaulroy\appdata\local\continuum\anaconda3\lib\site-packages (from fastavro)
Requirement already satisfied: setuptools>=18.0 in c:\users\neelotpaulroy\appdata\local\continuum\anaconda3\lib\site-packages (from fastavro)

So how do i solve this.

**Comment by andrewstevenson** [comment]
@pederpansen We aren't supporting this anymore. We have a python library coming out soon for Lenses, that lets you manage everything in your Kafka clusters plus SQL support for rest and websocket coming soon.
